### ISSUE TITLE
subpart inference?

### ISSUE THREAD

**Issue by joshmyersdean** [berkeley-hipie/HIPIE#11]
Hello! 

Thank you for this great work! Is there any easy way to test subpart inference? Also is there a preferred way to fine-tune?

Thank you!

**Comment by jacklishufan** [comment]
https://github.com/berkeley-hipie/HIPIE/blob/1e3b657e158379b2ad391346bdc6070c666e8298/projects/HIPIE/hipie/demo_lib/part_segm_demo.py#L314
Him our predictor will generate both part and subparts. In particular
`output_refined` is subparts and `output_coarse` is parts

**Comment by joshmyersdean** [comment]
thank you!
