### ISSUE TITLE
Adding new dataset

### ISSUE THREAD

**Issue by joshmyersdean** [berkeley-hipie/HIPIE#13]
Hello!

I was wondering you had documentation on the best way to add a dataset? It's not entirely clear from the current documentation.

Thank you!

**Comment by KKallidromitis** [comment]
Hi, we apologize for the delay. To add a custom dataset you can follow the detectron2 [documentation](https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html) and use standard COCO format.

Please make sure to have a labels file in `projects/HIPIE/hipie/data/datasets/openseg_labels` and a register file in `projects/HIPIE/hipie/data/datasets/` along the lines of the existing datasets. For a mapper you can use `projects/HIPIE/hipie/data/coco_dataset_mapper_uni.py` and add you dataset and name that can be used to select it.

**Comment by joshmyersdean** [comment]
This missed my email, thanks so much!
