### ISSUE TITLE
weight files missing

### ISSUE THREAD

**Issue by laxmaniron** [berkeley-hipie/HIPIE#17]
the provided link https://drive.google.com/drive/folders/1_kD3XILU1DC8uGn4vMGHgglDVlCl1U0W , doesn't have weight files,
can you provide the link to weight files

**Comment by SeanCraven314** [comment]
Hi I found them here, https://drive.google.com/drive/folders/1HEmCCRaWv6CEkim-PY6Qv4jGtdKvw8VH.

**Comment by KKallidromitis** [comment]
Moved: https://huggingface.co/KonstantinosKK/HIPIE
