### ISSUE TITLE
Missing ckpt

### ISSUE THREAD

**Issue by davidhanx** [berkeley-hipie/HIPIE#2]
![image](https://github.com/berkeley-hipie/HIPIE/assets/86959032/449935f9-6b03-4bdd-b3bb-8268af48a614)

Great work! But there seems to be one ckpt missing~

**Comment by KKallidromitis** [comment]
Thank you! This link can be used to download the checkpoints: https://huggingface.co/KonstantinosKK/HIPIE

**Comment by davidhanx** [comment]
Thank you so much!
