### ISSUE TITLE
Train code?

### ISSUE THREAD

**Issue by shipengai** [berkeley-hipie/HIPIE#3]
Good job!
Is there the plan to release training code?
Thanks

**Comment by shipengai** [comment]
One month？

**Comment by KKallidromitis** [comment]
Hi, we are currently training some improved weights and are planning to get internal permission to release the full code.

**Comment by shipengai** [comment]
Thanks for your reply. 
Acknowledgments about using other code is may suggested in Readme.

**Comment by baoxiaoyi** [comment]
hi! Is there the plan to release training code in September?

**Comment by KKallidromitis** [comment]
Hi we have a new pipeline implemented which we are currently testing and are expected to release the training code and improved weights in the next two to three weeks.

**Comment by baoxiaoyi** [comment]
> Hi we have a new pipeline implemented which we are currently testing and are expected to release the training code and improved weights in the next two to three weeks.

How do you prepare the pascal-part datasets? Can you upload your code of producing the training_pano and training_merged? Great thanks

**Comment by yahooo-m** [comment]
Hi, when will your group release the training code?

**Comment by jacklishufan** [comment]
Hi all. The training code and evaluation code have been released
