### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorLis

### ISSUE THREAD

**Issue by Bean95zx** [berkeley-hipie/HIPIE#5]
why show this error  wheni use the costumn image ?
![image](https://github.com/berkeley-hipie/HIPIE/assets/44997999/1837a68a-91b9-4e1e-99e0-9a17aafe06d1)

**Comment by KKallidromitis** [comment]
Hi, it is likely that mask['output_refined'] contains an empty tensor. This can be caused if there is no identified objects in the image. For images similar to the ones the model was trained on, this can be resolved by ensuring the shape of the image is reasonable (e.g. 1024 x 1024). If the image contains a significant domain shift then further fine-tuning is needed.
